// d4-6-one-middle-one-high - one random middle value on every face, one face highest
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d4", ["3", "3", "4", "3"], part = "all");
