// d10-4-random-bottom-third - random values from the bottom third
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d10", ["2", "3", "0", "1", "3", "2", "1", "0", "0", "0"], part = "all");
