// d10-5-random-middle-third - random values from the middle third
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d10", ["4", "5", "4", "6", "4", "3", "3", "4", "3", "6"], part = "all");
