// d10-3-random-top-third - random values from the top third
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d10", ["6", "6", "7", "7", "8", "7", "8", "6", "9", "6"], part = "all");
