// d10-2-all-high-one-low - every face highest, one face lowest
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d10", ["9", "9", "9", "9", "9", "9", "9", "0", "9", "9"], part = "all");
