#!/usr/bin/env python3
"""Generate the rigged dice sets.

Builds six rigged variants of every die type, writes a wrapper .scad per die
that feeds face labels into dice.scad, and renders each one to STL.

    ./generate.py                       # everything
    ./generate.py --type d20 d10        # only those die types
    ./generate.py --variant 1 3         # only those variants
    ./generate.py --seed 12345          # different random draws
    ./generate.py --dry-run             # print the face labels, render nothing

Output lands in dice/<type>/<variant>.stl, with the exact face labels of every
die recorded in dice/manifest.json so a print can be reproduced later.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import json
import math
import os
import random
import subprocess
import sys
import time
from pathlib import Path

import mmu3mf

HERE = Path(__file__).resolve().parent
OUT = HERE / "dice"
# Wrappers live in dice/<type>/, so they reach dice.scad two levels up. Kept
# relative deliberately: an absolute path would bake this machine's home
# directory into every generated file and break for anyone else.
SCAD_LIB = "../../dice.scad"
# Path to the OpenSCAD binary. Override with the OPENSCAD environment variable
# or --openscad; build.sh sets it for you.
DEFAULT_OPENSCAD = Path.home() / "3DObjects" / "OpenSCAD.AppImage"
OPENSCAD = Path(os.environ.get("OPENSCAD") or DEFAULT_OPENSCAD)

DEFAULT_SEED = 20250521

# Display colors baked into the 3MF so the parts are distinguishable on load.
# They are only a preview: the actual print uses whatever filament sits in the
# slot each part is assigned to (body = 1, numbers = 2).
BODY_COLOR = "#28323CFF"
NUMBER_COLOR = "#E8B54AFF"

# Die types. `values` are the face values in their natural order; `geometry` is
# the solid dice.scad should build (the percentile die is a d10 with different
# labels).
DICE = {
    "d4":     {"geometry": "d4",  "values": [str(n) for n in range(1, 5)]},
    "d6":     {"geometry": "d6",  "values": [str(n) for n in range(1, 7)]},
    "d8":     {"geometry": "d8",  "values": [str(n) for n in range(1, 9)]},
    "d10":    {"geometry": "d10", "values": [str(n) for n in range(0, 10)]},
    "d10x10": {"geometry": "d10", "values": [f"{n*10:02d}" for n in range(0, 10)]},
    "d12":    {"geometry": "d12", "values": [str(n) for n in range(1, 13)]},
    "d20":    {"geometry": "d20", "values": [str(n) for n in range(1, 21)]},
}

VARIANTS = {
    1: ("all-low-one-high",    "every face lowest, one face highest"),
    2: ("all-high-one-low",    "every face highest, one face lowest"),
    3: ("random-top-third",    "random values from the top third"),
    4: ("random-bottom-third", "random values from the bottom third"),
    5: ("random-middle-third", "random values from the middle third"),
    6: ("one-middle-one-high", "one random middle value on every face, one face highest"),
}


def thirds(values: list[str]) -> dict[str, list[str]]:
    """Split face values into overlapping thirds, inclusive of the edges.

    Face counts are rarely divisible by three, so each third is rounded up and
    the middle is centered. Values on a boundary belong to both neighbouring
    thirds, which is intentional.
    """
    n = len(values)
    cut = math.ceil(n / 3)
    return {
        "bottom": values[:cut],
        "middle": values[math.floor(n / 3) : math.ceil(2 * n / 3)],
        "top": values[n - cut :],
    }


def build_labels(die: dict, variant: int, rng: random.Random) -> list[str]:
    """The label for every numbered position on one die.

    Usually one per face, but the d4 is numbered at its corners (see dice.scad),
    so its four labels belong to vertices. Either way a d4 gets four.
    """
    values = die["values"]
    n = len(values)
    low, high = values[0], values[-1]
    part = thirds(values)

    if variant == 1:
        labels = [low] * n
        labels[rng.randrange(n)] = high
    elif variant == 2:
        labels = [high] * n
        labels[rng.randrange(n)] = low
    elif variant == 3:
        labels = [rng.choice(part["top"]) for _ in range(n)]
    elif variant == 4:
        labels = [rng.choice(part["bottom"]) for _ in range(n)]
    elif variant == 5:
        labels = [rng.choice(part["middle"]) for _ in range(n)]
    elif variant == 6:
        labels = [rng.choice(part["middle"])] * n
        labels[rng.randrange(n)] = high
    else:
        raise ValueError(f"unknown variant {variant}")
    return labels


def wrapper_scad(geometry: str, labels: list[str], name: str, desc: str,
                 part: str = "all") -> str:
    joined = ", ".join(f'"{v}"' for v in labels)
    return (
        f"// {name} - {desc}\n"
        f"// Generated by generate.py; edit that instead of this file.\n"
        f"use <{SCAD_LIB}>;\n\n"
        f"die(\"{geometry}\", [{joined}], part = \"{part}\");\n"
    )


def openscad(args: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run([str(OPENSCAD), "--backend=manifold"] + args,
                          capture_output=True, text=True)


def render(job: dict) -> dict:
    """Run OpenSCAD over one die's wrapper files. Returns the job with results."""
    start = time.monotonic()
    job["ok"] = True
    for scad, stl in job["outputs"]:
        proc = openscad(["-o", str(stl), "--export-format", "binstl",
                         str(scad)])
        if proc.returncode != 0 or not stl.exists():
            job["ok"] = False
            job["error"] = (proc.stderr or proc.stdout).strip()[-800:]
            break
    if job["ok"] and job["threemf"]:
        try:
            stats = mmu3mf.pack(
                job["threemf"],
                [("body", job["outputs"][0][1], BODY_COLOR),
                 ("numbers", job["outputs"][1][1], NUMBER_COLOR)],
                job["name"])
            job["stats"] = stats
            open_parts = [p["name"] for p in stats["parts"] if not p["closed"]]
            if open_parts:
                job["ok"] = False
                job["error"] = f"part(s) not watertight: {', '.join(open_parts)}"
        except (ValueError, OSError) as exc:
            job["ok"], job["error"] = False, str(exc)
        # The part files are scaffolding for the 3MF unless asked for directly;
        # the die's own .scad stays behind as the record of what was built.
        if not job["keep_parts"]:
            for scad, stl in job["outputs"]:
                stl.unlink(missing_ok=True)
                scad.unlink(missing_ok=True)

    job["seconds"] = time.monotonic() - start
    job["bytes"] = sum(f.stat().st_size for f in job["files"] if f.exists())
    if not job["ok"]:
        return job

    # A rigged die hides most of its faces from any one angle, so the preview is
    # two opposing views side by side rather than a single render.
    if job["preview"]:
        shots = []
        for i, camera in enumerate(("0,0,0,60,0,25,90", "0,0,0,60,0,205,90")):
            shot = job["png"].with_suffix(f".{i}.png")
            openscad(["-o", str(shot), "--imgsize=400,400",
                      f"--camera={camera}", "--colorscheme=Tomorrow",
                      str(job["record"])])
            shots.append(shot)
        stitch(shots, job["png"])
        for shot in shots:
            shot.unlink(missing_ok=True)
    return job


def stitch(shots: list[Path], out: Path) -> None:
    """Join the preview renders horizontally. Skipped if Pillow is missing."""
    try:
        from PIL import Image
    except ImportError:
        return
    images = [Image.open(s) for s in shots if s.exists()]
    if not images:
        return
    w, h = images[0].size
    sheet = Image.new("RGB", (w * len(images), h), "white")
    for i, image in enumerate(images):
        sheet.paste(image, (w * i, 0))
    sheet.save(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--type", nargs="+", choices=sorted(DICE), default=sorted(DICE),
                    help="die types to build (default: all)")
    ap.add_argument("--variant", nargs="+", type=int, choices=sorted(VARIANTS),
                    default=sorted(VARIANTS), help="variants to build (default: all)")
    ap.add_argument("--seed", type=int, default=DEFAULT_SEED,
                    help=f"random seed (default: {DEFAULT_SEED})")
    ap.add_argument("--openscad", type=Path,
                    help=f"path to the OpenSCAD binary (default: $OPENSCAD, "
                         f"else {DEFAULT_OPENSCAD})")
    ap.add_argument("--jobs", type=int, default=max(1, (os.cpu_count() or 4) // 2),
                    help="parallel OpenSCAD renders")
    ap.add_argument("--3mf", dest="threemf", action="store_true",
                    help="pack each die into one 3MF with the numbers assigned to "
                         "filament 2, ready to print on an AMS")
    ap.add_argument("--split", action="store_true",
                    help="emit body+numbers part STLs for a two-color AMS print "
                         "instead of one combined STL")
    ap.add_argument("--preview", action="store_true",
                    help="also render a two-sided PNG next to each STL")
    ap.add_argument("--dry-run", action="store_true",
                    help="print the face labels without rendering")
    args = ap.parse_args()

    if args.openscad:
        global OPENSCAD
        OPENSCAD = args.openscad

    if not args.dry_run and not OPENSCAD.exists():
        print(f"OpenSCAD not found at {OPENSCAD}\n"
              f"Set the OPENSCAD environment variable or pass --openscad.",
              file=sys.stderr)
        return 1

    jobs, manifest = [], []
    for type_name in args.type:
        die = DICE[type_name]
        for variant in args.variant:
            slug, desc = VARIANTS[variant]
            # Seed per die so that rendering a subset gives the same faces as a
            # full run - handy when reprinting a single die.
            rng = random.Random(f"{args.seed}:{type_name}:{variant}")
            labels = build_labels(die, variant, rng)

            name = f"{type_name}-{variant}-{slug}"
            folder = OUT / type_name
            folder.mkdir(parents=True, exist_ok=True)

            # Every die keeps a <name>.scad recording exactly what it is, whether
            # or not that is the file we render from.
            record = folder / f"{name}.scad"
            record.write_text(wrapper_scad(die["geometry"], labels, name, desc))

            # A single combined STL, or a body/numbers pair to load as two parts
            # of one object for a two-material AMS print.
            parts = ["body", "numbers"] if (args.split or args.threemf) else ["all"]
            outputs = []
            for part in parts:
                if part == "all":
                    outputs.append((record, folder / f"{name}.stl"))
                    continue
                scad = folder / f"{name}-{part}.scad"
                scad.write_text(
                    wrapper_scad(die["geometry"], labels, name, desc, part))
                outputs.append((scad, folder / f"{name}-{part}.stl"))

            threemf = folder / f"{name}.3mf" if args.threemf else None
            files = [threemf] if threemf else []
            if args.split or not threemf:
                files += [stl for _, stl in outputs]
            jobs.append({"name": name, "outputs": outputs, "threemf": threemf,
                         "record": record, "keep_parts": args.split, "files": files,
                         "png": folder / f"{name}.png", "preview": args.preview})
            manifest.append({
                "name": name, "type": type_name, "variant": variant,
                "description": desc, "labels": labels,
                "parts": parts,
                "numbering": "corner" if type_name == "d4" else "face",
                "distinct": sorted(set(labels), key=int),
            })
            print(f"{name:38} {' '.join(labels)}")

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "manifest.json").write_text(json.dumps(
        {"seed": args.seed, "dice": manifest}, indent=2) + "\n")

    if args.dry_run:
        print(f"\n{len(jobs)} dice (dry run, nothing rendered)")
        return 0

    print(f"\nRendering {len(jobs)} STLs with {args.jobs} workers...")
    failures, start = [], time.monotonic()
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as pool:
        for i, job in enumerate(pool.map(render, jobs), 1):
            status = "ok" if job["ok"] else "FAILED"
            size = job["bytes"] / 1e6
            print(f"  [{i}/{len(jobs)}] {job['name']:38} {status:6} "
                  f"{job['seconds']:5.1f}s {size:5.1f} MB")
            if not job["ok"]:
                failures.append(job)

    print(f"\n{len(jobs) - len(failures)}/{len(jobs)} rendered "
          f"in {time.monotonic() - start:.0f}s -> {OUT}")
    for job in failures:
        print(f"\n{job['name']} failed:\n{job.get('error', '')}", file=sys.stderr)
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
