// d12-2-all-high-one-low - every face highest, one face lowest
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d12", ["12", "12", "12", "12", "12", "12", "12", "12", "12", "1", "12", "12"], part = "all");
