// d12-5-random-middle-third - random values from the middle third
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d12", ["8", "6", "6", "6", "7", "5", "8", "8", "6", "6", "5", "7"], part = "all");
