// d12-4-random-bottom-third - random values from the bottom third
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d12", ["1", "4", "1", "2", "1", "3", "1", "2", "2", "4", "3", "3"], part = "all");
