// d12-6-one-middle-one-high - one random middle value on every face, one face highest
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d12", ["8", "8", "8", "8", "8", "8", "8", "8", "8", "8", "12", "8"], part = "all");
