// d12-3-random-top-third - random values from the top third
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d12", ["10", "10", "12", "10", "12", "9", "11", "12", "12", "11", "9", "9"], part = "all");
