// d10x10-5-random-middle-third - random values from the middle third
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d10", ["30", "60", "40", "50", "40", "30", "40", "30", "30", "30"], part = "all");
