// d10x10-2-all-high-one-low - every face highest, one face lowest
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d10", ["00", "90", "90", "90", "90", "90", "90", "90", "90", "90"], part = "all");
