// d10x10-3-random-top-third - random values from the top third
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d10", ["60", "60", "90", "60", "70", "80", "80", "90", "80", "70"], part = "all");
