// d10x10-4-random-bottom-third - random values from the bottom third
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d10", ["10", "10", "00", "10", "00", "30", "20", "20", "10", "30"], part = "all");
