// d10x10-6-one-middle-one-high - one random middle value on every face, one face highest
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d10", ["50", "50", "50", "50", "50", "90", "50", "50", "50", "50"], part = "all");
