// d10x10-1-all-low-one-high - every face lowest, one face highest
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d10", ["00", "00", "00", "00", "90", "00", "00", "00", "00", "00"], part = "all");
