// d8-1-all-low-one-high - every face lowest, one face highest
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d8", ["1", "1", "1", "1", "1", "8", "1", "1"], part = "all");
