// d8-2-all-high-one-low - every face highest, one face lowest
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d8", ["1", "8", "8", "8", "8", "8", "8", "8"], part = "all");
