// d8-3-random-top-third - random values from the top third
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d8", ["6", "7", "7", "8", "7", "7", "7", "6"], part = "all");
