// d8-4-random-bottom-third - random values from the bottom third
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d8", ["2", "2", "3", "3", "3", "3", "2", "1"], part = "all");
