// d8-5-random-middle-third - random values from the middle third
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d8", ["6", "5", "3", "4", "5", "5", "4", "5"], part = "all");
