// d8-6-one-middle-one-high - one random middle value on every face, one face highest
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d8", ["4", "4", "4", "4", "8", "4", "4", "4"], part = "all");
