// d20-2-all-high-one-low - every face highest, one face lowest
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d20", ["20", "20", "20", "20", "20", "20", "20", "20", "20", "20", "20", "20", "20", "20", "20", "20", "20", "20", "20", "1"], part = "all");
