// d20-3-random-top-third - random values from the top third
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d20", ["18", "19", "17", "17", "14", "20", "14", "15", "14", "16", "18", "15", "15", "16", "18", "19", "15", "15", "18", "18"], part = "all");
