// d20-6-one-middle-one-high - one random middle value on every face, one face highest
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d20", ["14", "14", "14", "14", "14", "14", "14", "14", "14", "14", "14", "14", "14", "14", "14", "14", "14", "14", "20", "14"], part = "all");
