// d20-4-random-bottom-third - random values from the bottom third
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d20", ["3", "5", "3", "5", "5", "7", "5", "5", "5", "4", "7", "3", "4", "6", "6", "1", "1", "4", "1", "3"], part = "all");
