// d20-1-all-low-one-high - every face lowest, one face highest
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d20", ["1", "1", "1", "20", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1"], part = "all");
