// d20-5-random-middle-third - random values from the middle third
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d20", ["12", "9", "7", "8", "7", "10", "8", "10", "8", "9", "13", "9", "9", "7", "13", "13", "14", "13", "9", "9"], part = "all");
