#!/usr/bin/env python3
"""Compose the self-contained MakerWorld customizer file from ../dice.scad.

MakerWorld's Parametric Model Maker takes a single .scad and drives it through
the OpenSCAD Customizer, which only reads top-level variables in that one file.
It cannot follow `use <../dice.scad>`, so the geometry has to be inlined.

Rather than keep a hand-copied duplicate that drifts, this script splices the
library half of dice.scad (everything from the size presets down to, but not
including, its demo render) underneath a Customizer front end. dice.scad stays
the single source of truth for the geometry.

    ./build_makerworld.py            # writes dice_customizer.scad
"""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
LIBRARY = HERE.parent / "dice.scad"
OUTPUT = HERE / "dice_customizer.scad"

# Slice markers in dice.scad. The tunables above the first are redeclared as
# Customizer parameters, and the demo render at the second is dropped.
START = "// ------------------------------------------------------------ size presets --"
END = "// Demo render."

MAX_FACES = 20

# Default face text, so the model opens as a plain 1..20 d20.
DEFAULTS = {i: str(i) for i in range(1, MAX_FACES + 1)}

HEADER = '''/*------------------------------------------------------------------------------
Rigged dice - parametric dice with your own numbers on every face

Pick the number of sides, then type whatever you want on each face: repeat a
value to load the die, use 00-90 for a percentile d10, or use letters and
symbols instead of numbers.

  d4   uses faces 1-4      d10  uses faces 1-10
  d6   uses faces 1-6      d12  uses faces 1-12
  d8   uses faces 1-8      d20  uses faces 1-20

Faces past the die's side count are ignored.

The d4 is numbered at its corners the way a commercial d4 is, so its four
values belong to the corners: whichever corner points up reads the same on all
three visible faces.

Set Colors to dual and the body and the numbers come out as two separate
colors in one model. They are exact complements, so the numbers sit flush in
their recesses with no gap and no overlap.

The die is placed with one face flat on the build plate, ready to print.

Generated from dice.scad by build_makerworld.py - do not edit this file
directly, edit dice.scad instead.

Public domain - CC0 1.0. Do whatever you like with it, no credit required.
https://github.com/PrismaticDispersion/rigged-dice
------------------------------------------------------------------------------*/

/* [Die] */

// Number of sides
sides = 20; // [4:d4, 6:d6, 8:d8, 10:d10, 12:d12, 20:d20]

// Single color, or the body and the numbers as two separate colors.
colors = "dual"; // [single:Single color, dual:Dual color]

// Color of the die body. Preview only - you pick the real filament when you
// print, this just decides which slot the part lands in.
body_color = "white"; // [white, black, red, orange, gold, green, blue, purple, silver]

// Color of the numbers.
number_color = "black"; // [black, white, red, orange, gold, green, blue, purple, silver]

// Overall size in mm - the largest dimension, as you would measure it with
// calipers. 0 keeps the standard size for this die.
die_size = 0; // [0:60]

/* [Numbers] */
'''

STYLE = '''
/* [Style] */

// Font. These three ship with OpenSCAD, so they render anywhere.
font_family = "Liberation Sans"; // [Liberation Sans, Liberation Serif, Liberation Mono]

// Font weight.
font_style = "Bold"; // [Bold, Regular, Italic, Bold Italic]

// Advanced: any other font installed on the renderer, given in full, such as
// "DejaVu Sans:style=Bold". Leave empty to use the two settings above. A font
// that is not installed falls back to another one silently, so check the
// preview if you change this.
font_custom = "";

// Size of the numbers, as a multiple of the automatic fit.
text_scale = 1.25; // [0.5:0.05:2.0]

// How deep the numbers are cut into the faces, mm.
text_depth = 0.9; // [0.2:0.1:2.0]

// Rounding of the corners and edges, mm.
rounding = 1.2; // [0.2:0.1:4.0]

// Add a trailing dot to 6 and 9 so they can be told apart.
mark_6_and_9 = true;

// Smoothness of the rounded corners. Higher is prettier but slower.
smoothness = 48; // [12:4:96]

/* [d4 corner numbers] */

// How far the d4 numbers sit toward their corners. Past ~0.55 they start
// riding onto the rounded edges.
d4_corner_offset = 0.48; // [0.2:0.01:0.7]

// Size of the d4 corner numbers, which share each face three ways.
d4_text_scale = 0.80; // [0.4:0.05:1.2]

/* [Hidden] */

// Assembled from the two dropdowns above. Kept out of the Customizer because a
// full font spec contains a colon, and the Customizer reads a colon inside a
// dropdown as the separator between a value and its display label - so
// "Liberation Sans:style=Bold" as a dropdown entry would quietly set the font
// to "Liberation Sans" and drop the weight.
font = font_custom != "" ? font_custom
                         : str(font_family, ":style=", font_style);

// Faces past the selected side count are ignored.
all_faces = [{face_list}];

// Customizer gives us free text, but the layout is designed around one or two
// characters; anything longer is trimmed rather than allowed to overflow.
function clip(s) = len(s) <= 2 ? s : str(s[0], s[1]);

function die_type(n) =
      n == 4  ? "d4"
    : n == 6  ? "d6"
    : n == 8  ? "d8"
    : n == 10 ? "d10"
    : n == 12 ? "d12"
    : n == 20 ? "d20"
    : undef;

type = die_type(sides);
labels = [for (i = [0:sides - 1]) clip(all_faces[i])];

// --- sitting the die flat on the build plate --------------------------------
// die() builds every solid centred on the origin in its own natural pose, which
// leaves most of them balanced on a vertex. Printing wants a face on the plate,
// so one face is rotated to point straight down and the die is dropped onto
// z = 0. Any face will do: within a die type they are all congruent.

// The face that ends up on the plate, and the rotation taking it onto -Z. The
// cross product vanishes when that normal already lies along Z, so fall back to
// any perpendicular axis - that case still needs the 180 turn when it points up.
function down_normal(t) = face_normal(vertices(t), faces(t)[0]);
function tip_axis(n) = let (a = cross(n, [0, 0, -1])) norm(a) < 1e-9 ? [1, 0, 0] : a;
function tip_angle(n) = acos(max(-1, min(1, n * [0, 0, -1])));

// Rodrigues rotation matrix, so the vertices can be measured in the pose they
// will actually print in rather than the pose they were defined in.
function rodrigues(k, a) =
    let (u = unit(k), c = cos(a), s = sin(a), t = 1 - c,
         x = u[0], y = u[1], z = u[2])
    [[t*x*x + c,   t*x*y - s*z, t*x*z + s*y],
     [t*x*y + s*z, t*y*y + c,   t*y*z - s*x],
     [t*x*z - s*y, t*y*z + s*x, t*z*z + c]];

// Vertices scaled the way die() scales them, then rotated face-down.
function placed_vertices(t) =
    let (n = down_normal(t),
         r = rodrigues(tip_axis(n), tip_angle(n)),
         sf = (size_mm(t) / 2 - rounding) / max([for (p = vertices(t)) norm(p)]))
    [for (p = vertices(t)) r * (p * sf)];

// How far to lift the die so its lowest surface rests on the plate. The body is
// a hull of spheres, so the printed surface sits `rounding` below the lowest
// vertex centre.
function rest_height(t) = -min([for (p = placed_vertices(t)) p[2]]) + rounding;

// Largest dimension of the finished die in its printing pose, so that die_size
// means the size you would measure with calipers. Deliberately not the
// corner-to-corner figure the internal presets use - on a d6 those differ by
// the cube diagonal, a surprising way to lose 40%. The hull of spheres extends
// the bounding box by the sphere radius on each side.
function widest_mm(t) =
    let (v = placed_vertices(t))
    max(max([for (p = v) p[0]]) - min([for (p = v) p[0]]),
        max([for (p = v) p[1]]) - min([for (p = v) p[1]]),
        max([for (p = v) p[2]]) - min([for (p = v) p[2]])) + 2 * rounding;

// die() sizes from the per-type preset, so an explicit size is applied as a
// uniform scale. Everything scales with it, rounding and lettering included.
scale(die_size > 0 ? die_size / widest_mm(type) : 1)
translate([0, 0, rest_height(type)])
rotate(a = tip_angle(down_normal(type)), v = tip_axis(down_normal(type))) {
    if (colors == "dual") {
        // Body and numbers are exact complements, so together they are the
        // whole die - no overlap to fight over, no gap to leak through. Two
        // color() calls is all a dual-color model needs; the slicer maps
        // each to a filament.
        color(body_color)   die(type, labels, part = "body");
        color(number_color) die(type, labels, part = "numbers");
    } else {
        die(type, labels, part = "all");
    }
}

'''


def main() -> int:
    if not LIBRARY.exists():
        print(f"cannot find {LIBRARY}", file=sys.stderr)
        return 1

    text = LIBRARY.read_text()
    start = text.find(START)
    end = text.find(END)
    if start == -1 or end == -1:
        print("could not find the slice markers in dice.scad; they are:\n"
              f"  {START}\n  {END}", file=sys.stderr)
        return 1

    library = text[start:end].rstrip() + "\n"

    faces = "\n".join(
        f'// Face {i}\nface_{i} = "{DEFAULTS[i]}";\n'
        for i in range(1, MAX_FACES + 1))
    face_list = ", ".join(f"face_{i}" for i in range(1, MAX_FACES + 1))

    OUTPUT.write_text(HEADER + faces
                      + STYLE.replace("{face_list}", face_list)
                      + library)
    print(f"wrote {OUTPUT.relative_to(HERE.parent)} "
          f"({len(OUTPUT.read_text().splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
