#!/usr/bin/env python3
"""Compose the self-contained MakerWorld customizer file from ../dice.scad.

MakerWorld's Parametric Model Maker takes a single .scad and drives it through
the OpenSCAD Customizer, which only reads top-level variables in that one file.
It cannot follow `use <../dice.scad>`, so the geometry has to be inlined.

Rather than keep a hand-copied duplicate that drifts, this script splices the
library half of dice.scad (everything from the size presets down to, but not
including, its demo render) underneath a Customizer front end. dice.scad stays
the single source of truth for the geometry.

    ./build_makerworld.py            # writes dice_customizer.scad
"""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
LIBRARY = HERE.parent / "dice.scad"
OUTPUT = HERE / "dice_customizer.scad"

# Slice markers in dice.scad. The tunables above the first are redeclared as
# Customizer parameters, and the demo render at the second is dropped.
START = "// ------------------------------------------------------------ size presets --"
END = "// Demo render."

MAX_FACES = 20

# Default face text, so the model opens as a plain 1..20 d20.
DEFAULTS = {i: str(i) for i in range(1, MAX_FACES + 1)}

HEADER = '''/*------------------------------------------------------------------------------
Rigged dice - parametric dice with your own numbers on every face

Pick the number of sides, then type whatever you want on each face: repeat a
value to load the die, use 00-90 for a percentile d10, or use letters and
symbols instead of numbers.

  d4   uses faces 1-4      d10  uses faces 1-10
  d6   uses faces 1-6      d12  uses faces 1-12
  d8   uses faces 1-8      d20  uses faces 1-20

Faces past the die's side count are ignored.

The d4 is numbered at its corners the way a commercial d4 is, so its four
values belong to the corners: whichever corner points up reads the same on all
three visible faces.

For a two-colour print, generate the model twice - once as "body" and once as
"numbers" - and load the two files as parts of one object. They are exact
complements, so they need no aligning.

Generated from dice.scad by build_makerworld.py - do not edit this file
directly, edit dice.scad instead.

Code MIT, dice designs CC BY 4.0, Copyright 2026 Nathaniel Westlake
https://github.com/PrismaticDispersion/rigged-dice
------------------------------------------------------------------------------*/

/* [Die] */

// Number of sides
sides = 20; // [4:d4, 6:d6, 8:d8, 10:d10, 12:d12, 20:d20]

// Which part to build. Use body + numbers for a two-colour print.
part = "all"; // [all:Whole die, body:Body only (colour 1), numbers:Numbers only (colour 2)]

// Overall size in mm - the largest dimension, as you would measure it with
// calipers. 0 keeps the standard size for this die.
die_size = 0; // [0:60]

/* [Numbers] */
'''

STYLE = '''
/* [Style] */

// Font. Liberation Sans is always available; others may not render.
font = "Liberation Sans:style=Bold"; // [Liberation Sans:style=Bold, Liberation Sans, Liberation Serif:style=Bold, Liberation Mono:style=Bold, DejaVu Sans:style=Bold]

// Size of the numbers, as a multiple of the automatic fit.
text_scale = 1.25; // [0.5:0.05:2.0]

// How deep the numbers are cut into the faces, mm.
text_depth = 0.9; // [0.2:0.1:2.0]

// Rounding of the corners and edges, mm.
rounding = 1.2; // [0.2:0.1:4.0]

// Add a trailing dot to 6 and 9 so they can be told apart.
mark_6_and_9 = true;

// Smoothness of the rounded corners. Higher is prettier but slower.
smoothness = 48; // [12:4:96]

/* [d4 corner numbers] */

// How far the d4 numbers sit toward their corners. Past ~0.55 they start
// riding onto the rounded edges.
d4_corner_offset = 0.48; // [0.2:0.01:0.7]

// Size of the d4 corner numbers, which share each face three ways.
d4_text_scale = 0.80; // [0.4:0.05:1.2]

/* [Hidden] */

// Faces past the selected side count are ignored.
all_faces = [{face_list}];

// Customizer gives us free text, but the layout is designed around one or two
// characters; anything longer is trimmed rather than allowed to overflow.
function clip(s) = len(s) <= 2 ? s : str(s[0], s[1]);

function die_type(n) =
      n == 4  ? "d4"
    : n == 6  ? "d6"
    : n == 8  ? "d8"
    : n == 10 ? "d10"
    : n == 12 ? "d12"
    : n == 20 ? "d20"
    : undef;

type = die_type(sides);
labels = [for (i = [0:sides - 1]) clip(all_faces[i])];

// Largest dimension of the finished die, matching how die() scales it. Used so
// that die_size means the size you would measure, rather than the
// corner-to-corner figure the internal presets use - on a d6 those differ by a
// factor of the cube diagonal, which is a surprising way to lose 40%.
function widest_mm(t) =
    let (v = vertices(t),
         sf = (size_mm(t) / 2 - rounding) / max([for (p = v) norm(p)]))
    2 * (max([for (p = v) max(abs(p[0]), abs(p[1]), abs(p[2]))]) * sf + rounding);

// die() sizes from the per-type preset, so an explicit size is applied as a
// uniform scale. Everything scales with it, rounding and lettering included.
scale(die_size > 0 ? die_size / widest_mm(type) : 1)
    die(type, labels, part = part);

'''


def main() -> int:
    if not LIBRARY.exists():
        print(f"cannot find {LIBRARY}", file=sys.stderr)
        return 1

    text = LIBRARY.read_text()
    start = text.find(START)
    end = text.find(END)
    if start == -1 or end == -1:
        print("could not find the slice markers in dice.scad; they are:\n"
              f"  {START}\n  {END}", file=sys.stderr)
        return 1

    library = text[start:end].rstrip() + "\n"

    faces = "\n".join(
        f'// Face {i}\nface_{i} = "{DEFAULTS[i]}";\n'
        for i in range(1, MAX_FACES + 1))
    face_list = ", ".join(f"face_{i}" for i in range(1, MAX_FACES + 1))

    OUTPUT.write_text(HEADER + faces
                      + STYLE.replace("{face_list}", face_list)
                      + library)
    print(f"wrote {OUTPUT.relative_to(HERE.parent)} "
          f"({len(OUTPUT.read_text().splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
