/*------------------------------------------------------------------------------
Rigged dice - parametric dice with your own numbers on every face

Pick the number of sides, then type whatever you want on each face: repeat a
value to load the die, use 00-90 for a percentile d10, or use letters and
symbols instead of numbers.

  d4   uses faces 1-4      d10  uses faces 1-10
  d6   uses faces 1-6      d12  uses faces 1-12
  d8   uses faces 1-8      d20  uses faces 1-20

Faces past the die's side count are ignored.

The d4 is numbered at its corners the way a commercial d4 is, so its four
values belong to the corners: whichever corner points up reads the same on all
three visible faces.

For a two-colour print, generate the model twice - once as "body" and once as
"numbers" - and load the two files as parts of one object. They are exact
complements, so they need no aligning.

Generated from dice.scad by build_makerworld.py - do not edit this file
directly, edit dice.scad instead.

Code MIT, dice designs CC BY 4.0, Copyright 2026 Nathaniel Westlake
https://github.com/PrismaticDispersion/rigged-dice
------------------------------------------------------------------------------*/

/* [Die] */

// Number of sides
sides = 20; // [4:d4, 6:d6, 8:d8, 10:d10, 12:d12, 20:d20]

// Single colour, or the body and the numbers as two separate colours.
colours = "dual"; // [single:Single colour, dual:Dual colour]

// Colour of the die body. Preview only - you pick the real filament when you
// print, this just decides which slot the part lands in.
body_colour = "white"; // [white, black, red, orange, gold, green, blue, purple, silver]

// Colour of the numbers.
number_colour = "black"; // [black, white, red, orange, gold, green, blue, purple, silver]

// Overall size in mm - the largest dimension, as you would measure it with
// calipers. 0 keeps the standard size for this die.
die_size = 0; // [0:60]

/* [Numbers] */
// Face 1
face_1 = "1";

// Face 2
face_2 = "2";

// Face 3
face_3 = "3";

// Face 4
face_4 = "4";

// Face 5
face_5 = "5";

// Face 6
face_6 = "6";

// Face 7
face_7 = "7";

// Face 8
face_8 = "8";

// Face 9
face_9 = "9";

// Face 10
face_10 = "10";

// Face 11
face_11 = "11";

// Face 12
face_12 = "12";

// Face 13
face_13 = "13";

// Face 14
face_14 = "14";

// Face 15
face_15 = "15";

// Face 16
face_16 = "16";

// Face 17
face_17 = "17";

// Face 18
face_18 = "18";

// Face 19
face_19 = "19";

// Face 20
face_20 = "20";

/* [Style] */

// Font. These three ship with OpenSCAD, so they render anywhere.
font_family = "Liberation Sans"; // [Liberation Sans, Liberation Serif, Liberation Mono]

// Font weight.
font_style = "Bold"; // [Bold, Regular, Italic, Bold Italic]

// Advanced: any other font installed on the renderer, given in full, such as
// "DejaVu Sans:style=Bold". Leave empty to use the two settings above. A font
// that is not installed falls back to another one silently, so check the
// preview if you change this.
font_custom = "";

// Size of the numbers, as a multiple of the automatic fit.
text_scale = 1.25; // [0.5:0.05:2.0]

// How deep the numbers are cut into the faces, mm.
text_depth = 0.9; // [0.2:0.1:2.0]

// Rounding of the corners and edges, mm.
rounding = 1.2; // [0.2:0.1:4.0]

// Add a trailing dot to 6 and 9 so they can be told apart.
mark_6_and_9 = true;

// Smoothness of the rounded corners. Higher is prettier but slower.
smoothness = 48; // [12:4:96]

/* [d4 corner numbers] */

// How far the d4 numbers sit toward their corners. Past ~0.55 they start
// riding onto the rounded edges.
d4_corner_offset = 0.48; // [0.2:0.01:0.7]

// Size of the d4 corner numbers, which share each face three ways.
d4_text_scale = 0.80; // [0.4:0.05:1.2]

/* [Hidden] */

// Assembled from the two dropdowns above. Kept out of the Customizer because a
// full font spec contains a colon, and the Customizer reads a colon inside a
// dropdown as the separator between a value and its display label - so
// "Liberation Sans:style=Bold" as a dropdown entry would quietly set the font
// to "Liberation Sans" and drop the weight.
font = font_custom != "" ? font_custom
                         : str(font_family, ":style=", font_style);

// Faces past the selected side count are ignored.
all_faces = [face_1, face_2, face_3, face_4, face_5, face_6, face_7, face_8, face_9, face_10, face_11, face_12, face_13, face_14, face_15, face_16, face_17, face_18, face_19, face_20];

// Customizer gives us free text, but the layout is designed around one or two
// characters; anything longer is trimmed rather than allowed to overflow.
function clip(s) = len(s) <= 2 ? s : str(s[0], s[1]);

function die_type(n) =
      n == 4  ? "d4"
    : n == 6  ? "d6"
    : n == 8  ? "d8"
    : n == 10 ? "d10"
    : n == 12 ? "d12"
    : n == 20 ? "d20"
    : undef;

type = die_type(sides);
labels = [for (i = [0:sides - 1]) clip(all_faces[i])];

// --- sitting the die flat on the build plate --------------------------------
// die() builds every solid centred on the origin in its own natural pose, which
// leaves most of them balanced on a vertex. Printing wants a face on the plate,
// so one face is rotated to point straight down and the die is dropped onto
// z = 0. Any face will do: within a die type they are all congruent.

// The face that ends up on the plate, and the rotation taking it onto -Z. The
// cross product vanishes when that normal already lies along Z, so fall back to
// any perpendicular axis - that case still needs the 180 turn when it points up.
function down_normal(t) = face_normal(vertices(t), faces(t)[0]);
function tip_axis(n) = let (a = cross(n, [0, 0, -1])) norm(a) < 1e-9 ? [1, 0, 0] : a;
function tip_angle(n) = acos(max(-1, min(1, n * [0, 0, -1])));

// Rodrigues rotation matrix, so the vertices can be measured in the pose they
// will actually print in rather than the pose they were defined in.
function rodrigues(k, a) =
    let (u = unit(k), c = cos(a), s = sin(a), t = 1 - c,
         x = u[0], y = u[1], z = u[2])
    [[t*x*x + c,   t*x*y - s*z, t*x*z + s*y],
     [t*x*y + s*z, t*y*y + c,   t*y*z - s*x],
     [t*x*z - s*y, t*y*z + s*x, t*z*z + c]];

// Vertices scaled the way die() scales them, then rotated face-down.
function placed_vertices(t) =
    let (n = down_normal(t),
         r = rodrigues(tip_axis(n), tip_angle(n)),
         sf = (size_mm(t) / 2 - rounding) / max([for (p = vertices(t)) norm(p)]))
    [for (p = vertices(t)) r * (p * sf)];

// How far to lift the die so its lowest surface rests on the plate. The body is
// a hull of spheres, so the printed surface sits `rounding` below the lowest
// vertex centre.
function rest_height(t) = -min([for (p = placed_vertices(t)) p[2]]) + rounding;

// Largest dimension of the finished die in its printing pose, so that die_size
// means the size you would measure with calipers. Deliberately not the
// corner-to-corner figure the internal presets use - on a d6 those differ by
// the cube diagonal, a surprising way to lose 40%. The hull of spheres extends
// the bounding box by the sphere radius on each side.
function widest_mm(t) =
    let (v = placed_vertices(t))
    max(max([for (p = v) p[0]]) - min([for (p = v) p[0]]),
        max([for (p = v) p[1]]) - min([for (p = v) p[1]]),
        max([for (p = v) p[2]]) - min([for (p = v) p[2]])) + 2 * rounding;

// die() sizes from the per-type preset, so an explicit size is applied as a
// uniform scale. Everything scales with it, rounding and lettering included.
scale(die_size > 0 ? die_size / widest_mm(type) : 1)
translate([0, 0, rest_height(type)])
rotate(a = tip_angle(down_normal(type)), v = tip_axis(down_normal(type))) {
    if (colours == "dual") {
        // Body and numbers are exact complements, so together they are the
        // whole die - no overlap to fight over, no gap to leak through. Two
        // colour() calls is all a dual-colour model needs; the slicer maps
        // each to a filament.
        color(body_colour)   die(type, labels, part = "body");
        color(number_colour) die(type, labels, part = "numbers");
    } else {
        die(type, labels, part = "all");
    }
}

// ------------------------------------------------------------ size presets --

// Corner-to-corner diameter (circumscribed sphere) in mm, per die type.
// These give dice that sit at roughly standard tabletop sizes.
function size_mm(type) =
      type == "d4"  ? 24
    : type == "d6"  ? 27.7
    : type == "d8"  ? 22
    : type == "d10" ? 21
    : type == "d12" ? 25
    : type == "d20" ? 24
    : 24;

// -------------------------------------------------------------- geometry ----

phi = (1 + sqrt(5)) / 2;
iphi = 1 / phi;

// Pentagonal trapezohedron (the d10 shape).
// Two apexes on the Z axis plus two staggered rings of five vertices. The ratio
// between the apex height and the ring height is fixed by the requirement that
// each kite face be planar; see notes in README.md.
d10_h = 1.0;                     // apex height
d10_c = d10_h / 9.472136;        // ring height (+/-)

function vertices(type) =
      type == "d4" ? [[1,1,1], [1,-1,-1], [-1,1,-1], [-1,-1,1]]
    : type == "d6" ? [for (x = [1,-1], y = [1,-1], z = [1,-1]) [x,y,z]]
    : type == "d8" ? [[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]]
    : type == "d12" ? concat(
          [for (x = [1,-1], y = [1,-1], z = [1,-1]) [x,y,z]],
          [for (y = [iphi,-iphi], z = [phi,-phi]) [0,y,z]],
          [for (x = [iphi,-iphi], y = [phi,-phi]) [x,y,0]],
          [for (z = [iphi,-iphi], x = [phi,-phi]) [x,0,z]])
    : type == "d20" ? concat(
          [for (y = [1,-1], z = [phi,-phi]) [0,y,z]],
          [for (x = [1,-1], y = [phi,-phi]) [x,y,0]],
          [for (z = [1,-1], x = [phi,-phi]) [x,0,z]])
    : type == "d10" ? concat(
          [[0,0,d10_h], [0,0,-d10_h]],
          [for (i = [0:4]) [cos(i*72),      sin(i*72),      d10_c]],
          [for (i = [0:4]) [cos(i*72 + 36), sin(i*72 + 36), -d10_c]])
    : undef;

// Faces as lists of indices into vertices(type), wound counter-clockwise when
// seen from outside. Only the vertex positions matter for the body (it is a
// hull), but the numbering needs one entry per face and a correct plane.
function faces(type) =
      type == "d4" ? [[0,1,2],[0,3,1],[0,2,3],[1,3,2]]
    : type == "d6" ? [[0,1,3,2],[4,6,7,5],[0,4,5,1],[2,3,7,6],[0,2,6,4],[1,5,7,3]]
    : type == "d8" ? [[0,2,4],[2,1,4],[1,3,4],[3,0,4],
                      [2,0,5],[1,2,5],[3,1,5],[0,3,5]]
    // d10: index 0 = top apex, 1 = bottom apex, 2..6 = upper ring, 7..11 = lower
    : type == "d10" ? concat(
          [for (i = [0:4]) [0, 2 + i, 7 + i, 2 + (i+1)%5]],
          [for (i = [0:4]) [1, 7 + (i+1)%5, 2 + (i+1)%5, 7 + i]])
    : type == "d12" ? dodeca_faces()
    : type == "d20" ? icosa_faces()
    : undef;

// The d12 and d20 face lists are tedious to write out by hand and easy to get
// wrong, so they are derived from the geometry instead: every set of coplanar
// vertices at the face-plane distance is a face.
function dodeca_faces() = hull_faces("d12", 5);
function icosa_faces()  = hull_faces("d20", 3);

// Collect the vertices lying on each face plane. For a face-transitive solid
// centered on the origin, every face plane sits at the same distance `inr` from
// the center, and each face normal points at a distinct direction; we recover
// them from the vertex combinations rather than enumerating faces manually.
function hull_faces(type, n) =
    let (v = vertices(type),
         norms = face_normals(type),
         inr = plane_dist(type))
    [for (nv = norms)
        order_face([for (i = [0:len(v)-1]) if (abs(v[i] * nv - inr) < 1e-6) i],
                   v, nv)];

// All cyclic permutations of [a,b,c], over every sign combination of the
// non-zero entries. Generates the normal families below.
function cyclic(a, b, c) =
    [for (s = sign_combos([a,b,c]), k = [0:2]) [s[k % 3], s[(k+1) % 3], s[(k+2) % 3]]];

function sign_combos(p) =
    [for (x = p[0] == 0 ? [0] : [p[0], -p[0]],
          y = p[1] == 0 ? [0] : [p[1], -p[1]],
          z = p[2] == 0 ? [0] : [p[2], -p[2]]) [x,y,z]];

// Face normals. These are the vertex directions of the dual solid, but the dual
// has the opposite chirality to the vertex lists above, so they are spelled out
// rather than reusing vertices(): a dodecahedron face points along [0,phi,1],
// an icosahedron face along [1,1,1] or [1/phi,0,phi].
function face_normals(type) =
      type == "d12" ? [for (p = cyclic(0, phi, 1)) unit(p)]
    : type == "d20" ? concat(
          [for (p = sign_combos([1,1,1])) unit(p)],
          [for (p = cyclic(iphi, 0, phi)) unit(p)])
    : undef;

// Distance from the center to any face plane, for the solids built by
// hull_faces(). Derived from one known face plane and one vertex on it.
function plane_dist(type) =
      type == "d12" ? unit([0,phi,1]) * [1,1,1]
    : type == "d20" ? unit([1,1,1]) * [0,1,phi]
    : undef;

// Sort a face's vertex indices into a consistent winding around its normal, so
// that polyhedron() would accept them and centroids come out right.
function order_face(idx, v, nv) =
    let (c = vsum([for (i = idx) v[i]]) / len(idx),
         u = unit(v[idx[0]] - c),
         w = cross(nv, u))
    [for (p = sortkey([for (i = idx) [atan2((v[i]-c) * w, (v[i]-c) * u), i]])) p[1]];

// ------------------------------------------------------------- vector math --

function vsum(l, i = 0) = i >= len(l) ? [0,0,0] : l[i] + vsum(l, i + 1);
function unit(v) = v / norm(v);

// Insertion sort on the first element of each [key, value] pair.
function sortkey(l) =
    len(l) <= 1 ? l
    : let (pivot = l[0], rest = [for (i = [1:len(l)-1]) l[i]])
      concat(sortkey([for (e = rest) if (e[0] <  pivot[0]) e]),
             [pivot],
             sortkey([for (e = rest) if (e[0] >= pivot[0]) e]));

// Rotation matrix taking +Z onto `n`, with `up` pulled onto the face's +Y.
function orient(n, up) =
    let (z = unit(n),
         y = unit(up - z * (up * z)),
         x = cross(y, z))
    [[x[0], y[0], z[0], 0],
     [x[1], y[1], z[1], 0],
     [x[2], y[2], z[2], 0],
     [0, 0, 0, 1]];

// Which way is "up" when reading a face: world +Z, unless the face points that
// way already, in which case fall back to +Y.
function up_for(n) = abs(unit(n) * [0,0,1]) > 0.99 ? [0,1,0] : [0,0,1];

// Outward unit normal of a face, from the cross product of two of its edges.
// Note this is NOT the direction of the face centroid: on the d10 the kite
// faces are not centered on their own normal, so that shortcut puts the numbers
// on a tilted plane buried inside the solid.
function face_normal(v, f) =
    let (n = unit(cross(v[f[1]] - v[f[0]], v[f[2]] - v[f[0]])),
         c = vsum([for (i = f) v[i]]) / len(f))
    n * c < 0 ? -n : n;

// Radius of the largest circle that fits inside a face, in model units.
// Measured as the shortest distance from the centroid to an edge.
function face_inradius(v, f) =
    let (c = vsum([for (i = f) v[i]]) / len(f))
    min([for (j = [0:len(f)-1])
            let (a = v[f[j]], b = v[f[(j+1) % len(f)]])
            norm(cross(b - a, c - a)) / norm(b - a)]);

// ------------------------------------------------------------------ model ---

// Trailing period on 6 and 9 so a rolled die is not ambiguous.
function marked(label) =
    mark_6_and_9 && (label == "6" || label == "9") ? str(label, ".") : label;

// Text is sized to the inscribed circle of the face, then backed off for
// multi-character labels so wide numbers still fit.
function auto_font_size(label, fi) =
    fi * text_scale * (len(label) <= 1 ? 0.95 : 0.72);

// The d4 is read at the corner that points up, not at a face, so its numbers
// belong to vertices rather than faces: each of the four values is written three
// times, once on each face meeting its vertex. The three faces visible on a
// resting d4 therefore all show the same number at the apex.
function corner_numbered(type) = type == "d4";

// One number, cut into the face plane. `where` is a point on the unrounded face
// plane, `n` the face normal, `up` the in-plane direction the text reads toward.
module engrave(label, where, n, up, size) {
    // The hull pushes the real surface out by `rounding` past the face plane,
    // so follow the normal out to meet it.
    translate(where + n * rounding)
        multmatrix(orient(n, up))
            translate([0, 0, -text_depth])
                linear_extrude(text_depth * 2)
                    text(label, font = font, size = size,
                         halign = "center", valign = "center");
}

/*
`part` selects what gets rendered, so one definition serves both the
single-colour print and a two-material AMS print:

    "all"     the finished die, numbers recessed into it (default)
    "body"    same thing - the half an AMS print does in the body colour
    "numbers" just the plugs that fill those recesses, in the number colour

"body" and "numbers" are exact complements in the same coordinate frame, so
loading them as two parts of one object lines them up with no repositioning.
*/
module die(type, labels, part = "all") {
    v = vertices(type);
    f = faces(type);
    assert(!is_undef(v), str("unknown die type: ", type));
    slots = corner_numbered(type) ? len(v) : len(f);
    assert(len(labels) == slots,
           str(type, " needs ", slots, " labels but got ", len(labels),
               corner_numbered(type) ? " (one per corner)" : " (one per face)"));
    assert(part == "all" || part == "body" || part == "numbers",
           str("unknown part: ", part));

    // Scale so the corner-to-corner size matches the preset, rounding included.
    circum = max([for (p = v) norm(p)]);
    scale_f = (size_mm(type) / 2 - rounding) / circum;
    sv = [for (p = v) p * scale_f];

    // Body: hull of a sphere at every corner. Rounds corners and edges in one
    // step and keeps the faces perfectly flat in between.
    module body() {
        hull() for (p = sv) translate(p) sphere(r = rounding, $fn = smoothness);
    }

    // The raw number solids. They stick out past the surface, so they are always
    // either cut from the body or clipped back to it - never used on their own.
    module numbers() {
        for (i = [0:len(f)-1]) {
            n = face_normal(sv, f[i]);
            c = vsum([for (j = f[i]) sv[j]]) / len(f[i]);
            fi = face_inradius(sv, f[i]);

            if (corner_numbered(type)) {
                // Three numbers per face, one pushed out toward each corner and
                // rotated to read from the middle of the face outward - so the
                // number stands upright when its corner is the top of the die.
                for (j = f[i]) {
                    label = marked(labels[j]);
                    engrave(label, c + (sv[j] - c) * d4_corner_offset, n,
                            sv[j] - c,
                            auto_font_size(label, fi) * d4_text_scale);
                }
            } else {
                label = marked(labels[i]);
                engrave(label, c, n, up_for(n), auto_font_size(label, fi));
            }
        }
    }

    if (part == "numbers") {
        // Clipped to the body, so each plug stops flush with the face.
        intersection() { body(); numbers(); }
    } else {
        difference() { body(); numbers(); }
    }
}
