// d6-1-all-low-one-high - every face lowest, one face highest
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d6", ["1", "6", "1", "1", "1", "1"], part = "all");
