// d6-2-all-high-one-low - every face highest, one face lowest
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d6", ["6", "6", "6", "6", "1", "6"], part = "all");
