// d6-3-random-top-third - random values from the top third
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d6", ["6", "6", "6", "5", "6", "6"], part = "all");
