// d6-4-random-bottom-third - random values from the bottom third
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d6", ["1", "1", "2", "2", "1", "2"], part = "all");
