// d6-5-random-middle-third - random values from the middle third
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d6", ["3", "4", "4", "4", "3", "3"], part = "all");
