// d6-6-one-middle-one-high - one random middle value on every face, one face highest
// Generated by generate.py; edit that instead of this file.
use <../../dice.scad>;

die("d6", ["3", "3", "3", "3", "3", "6"], part = "all");
